services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - "8090:80"
        networks:
            - internal
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www/html/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf
        container_name: ping-nginx
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        networks:
            - internal
        volumes:
            - ./:/var/www/html/
            - ./docker/php-fpm/zzz-xdebug.ini:/usr/local/etc/php/conf.d/zzz-xdebug.ini
        environment:
            XDEBUG_CONFIG: discover_client_host=true client_host=host.docker.internal log_level=0
        container_name: ping-php
        expose:
            - "9000"
    mysql:
        container_name: ping-mysql
        restart: always
        image: mysql:9.0.1
        ports:
            - "3309:3306"
        environment:
            MYSQL_DATABASE: ping_db
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - internal
    mysql-testing:
        container_name: ping-mysql-testing
        restart: always
        image: mysql:9.0.1
        ports:
            - "3310:3306"
        environment:
            MYSQL_DATABASE: ping_db_testing
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_test_data:/var/lib/mysql
        networks:
            - internal
networks:
    internal:
        driver: bridge
volumes:
    mysql_data:
        driver: local
    mysql_test_data:
        driver: local

