name: pingApi
services:
    nginx:
        container_name: ping-nginx
        image: "nginx:stable-alpine"
        networks:
            - internal
        restart: unless-stopped
        tty: true
        ports:
            - "8090:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html
        depends_on:
            - mysql
            - php-fpm
    php-fpm:
        container_name: ping-php-fpm
        build:
            context: docker/php-fpm
            dockerfile: Dockerfile
        networks:
            - internal
        volumes:
            - ./:/var/www/html
        expose:
            - "9000"
    mysql:
        container_name: ping-mysql
        restart: always
        image: mysql:9.0.1
        ports:
            - "3316:3306"
        environment:
            MYSQL_DATABASE: ping_db
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - internal

    composer:
        container_name: ping-composer
        build:
            context: docker/composer
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - internal

    artisan:
        container_name: ping-artisan
        build:
            context: docker/php-fpm
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        entrypoint: ["php", "/var/www/html/artisan"]
        networks:
            - internal

networks:
    internal:
        driver: bridge

volumes:
    mysql_data:
        driver: local
